<<<<<<< HEAD
name: BeyondWartime
main: us.bemrose.mc.BeyondWartime.BeyondWartime
version: 0.1.3
startup: postworld
depend: [Vault]
commands:
  war:
    description: BeyondWartime
    usage: /war <join|stats|teams>

=======
name: BeyondWartime
main: us.bemrose.mc.BeyondWartime.BeyondWartime
version: 0.1.3
startup: postworld
depend: [Vault]
commands:
  war:
    description: BeyondWartime
    usage: /war <join|stats|teams>

>>>>>>> 7c51fb5caeb5d69a7bcd72988839434296bb287a
